// src/components/common/Footer.jsx
import React from 'react';

const Footer = () => {
  return (
    <footer className="w-full bg-black text-white mt-14 py-4 px-4">
      <div className="w-full max-w-[1440px] mx-auto">
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center space-y-8 lg:space-y-0 mb-6">
          
          {/* Logo and Social Media Section */}
          <div className="flex flex-col items-start space-y-16 lg:space-y-16">
            {/* Logo */}
            <img 
              src="/images/img_footer_logo.png" 
              alt="Acentria Global Consulting Footer Logo" 
              className="w-[180px] sm:w-[200px] lg:w-[240px] h-auto"
            />
            
            {/* Social Media Icons */}
            <div className="flex items-center space-x-4">
              <a href="#" className="hover:opacity-80 transition-opacity" aria-label="Facebook">
                <img 
                  src="/images/img_mingcute_facebook_fill.svg" 
                  alt="Facebook" 
                  className="w-6 h-6"
                />
              </a>
              <a href="#" className="hover:opacity-80 transition-opacity" aria-label="Instagram">
                <img 
                  src="/images/img_line_md_instagram.svg" 
                  alt="Instagram" 
                  className="w-6 h-6"
                />
              </a>
              <a href="#" className="hover:opacity-80 transition-opacity" aria-label="Twitter">
                <img 
                  src="/images/img_fa6_brands_square_x_twitter.svg" 
                  alt="Twitter" 
                  className="w-[22px] h-[22px]"
                />
              </a>
              <a href="#" className="hover:opacity-80 transition-opacity" aria-label="LinkedIn">
                <img 
                  src="/images/img_ion_logo_linkedin.svg" 
                  alt="LinkedIn" 
                  className="w-6 h-6"
                />
              </a>
              <a href="#" className="hover:opacity-80 transition-opacity" aria-label="TikTok">
                <img 
                  src="/images/img_mage_tiktok_circle.svg" 
                  alt="TikTok" 
                  className="w-6 h-6"
                />
              </a>
            </div>
          </div>

          {/* Links Section */}
          <div className="flex flex-col lg:flex-row justify-center items-start w-full lg:w-[68%] space-y-8 lg:space-y-0 lg:space-x-8">
            
            {/* Useful Links */}
            <div className="flex flex-col space-y-3 w-full lg:w-[52%]">
              <h3 className="text-xl font-bold font-['Inter'] text-white mb-2">Useful Links</h3>
              <ul className="space-y-7 ml-1">
                <li>
                  <a href="/" className="text-white hover:text-red-400 transition-colors text-[15px] font-semibold font-['Inter']">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:text-red-400 transition-colors text-[15px] font-semibold font-['Inter']">
                    Become Our Agent
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:text-red-400 transition-colors text-[15px] font-semibold font-['Inter']">
                    Access Account
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:text-red-400 transition-colors text-[15px] font-semibold font-['Inter']">
                    Technical Support
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:text-red-400 transition-colors text-[15px] font-semibold font-['Inter']">
                    Terms & Conditions
                  </a>
                </li>
              </ul>
            </div>

            {/* Services */}
            <div className="flex flex-col space-y-3 w-full lg:w-[46%]">
              <h3 className="text-xl font-bold font-['Inter'] text-white mb-2 ml-1">Services</h3>
              <ul className="space-y-7">
                <li>
                  <a href="#" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                    <img 
                      src="/images/img_vector_red_900_18x14.svg" 
                      alt="Insurance icon" 
                      className="w-[14px] h-[18px]"
                    />
                    <span className="text-[15px] font-semibold font-['Inter']">Insurance</span>
                  </a>
                </li>
                <li>
                  <a href="#" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                    <img 
                      src="/images/img_group.svg" 
                      alt="Reinsurance icon" 
                      className="w-[14px] h-[14px]"
                    />
                    <span className="text-[15px] font-semibold font-['Inter']">Reinsurance</span>
                  </a>
                </li>
                <li>
                  <a href="#" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                    <img 
                      src="/images/img_group_red_900.svg" 
                      alt="Product Management icon" 
                      className="w-[14px] h-[14px]"
                    />
                    <span className="text-[15px] font-semibold font-['Inter']">Product Management</span>
                  </a>
                </li>
                <li>
                  <a href="#" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                    <img 
                      src="/images/img_vector_red_900_20x20.svg" 
                      alt="Technology icon" 
                      className="w-5 h-5"
                    />
                    <span className="text-[15px] font-semibold font-['Inter']">Technology</span>
                  </a>
                </li>
                <li>
                  <a href="#" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                    <img 
                      src="/images/img_vector_18x14.svg" 
                      alt="Investment icon" 
                      className="w-[14px] h-[18px]"
                    />
                    <span className="text-[15px] font-semibold font-['Inter']">Investment</span>
                  </a>
                </li>
              </ul>
            </div>
          </div>

          {/* Contact Us */}
          <div className="flex flex-col space-y-3 w-full lg:w-[30%]">
            <h3 className="text-xl font-bold font-['Inter'] text-white mb-2 ml-6 lg:ml-7">Contact Us</h3>
            <ul className="space-y-7">
              <li>
                <a href="tel:+254705200222" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                  <img 
                    src="/images/img_vector_red_900_18x18.svg" 
                    alt="Phone icon" 
                    className="w-[18px] h-[18px]"
                  />
                  <span className="text-[15px] font-semibold font-['Inter']">+254 705 200 222</span>
                </a>
              </li>
              <li>
                <a href="mailto:info@acesure.com" className="flex items-center space-x-2 text-white hover:text-red-400 transition-colors">
                  <img 
                    src="/images/img_ic_round_email.svg" 
                    alt="Email icon" 
                    className="w-6 h-6"
                  />
                  <span className="text-[15px] font-semibold font-['Inter']">info@acesure.com</span>
                </a>
              </li>
              <li>
                <div className="flex items-center space-x-3 text-white ml-1">
                  <img 
                    src="/images/img_vector_red_900_20x14.svg" 
                    alt="Address icon" 
                    className="w-[14px] h-5"
                  />
                  <span className="text-[15px] font-semibold font-['Inter']">P.O.Box 5864-00100 Nairobi</span>
                </div>
              </li>
              <li>
                <div className="flex items-center space-x-2 text-white ml-1">
                  <img 
                    src="/images/img_vector_red_900_20x16.svg" 
                    alt="Location icon" 
                    className="w-4 h-5"
                  />
                  <span className="text-[15px] font-semibold font-['Inter']">West Park Towers,Westlands</span>
                </div>
              </li>
            </ul>
          </div>
        </div>

        {/* Divider Line */}
        <div className="w-full h-[2px] bg-[#ed1e26] my-4"></div>

        {/* Copyright Section */}
        <div className="text-center space-y-3">
          <p className="text-[15px] font-medium font-['Poppins'] text-white">
            @ Copyright 2025 Acensure. All Rights Reserved
          </p>
          <p className="text-[15px] font-medium font-['Poppins'] text-white">
            Powered by Acensure Technologies
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer class="bg-black text-white py-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="grid grid-cols-1 lg:grid-cols-4 gap-8 mb-12">
        <!-- Logo and Social Media -->
        <div class="lg:col-span-1">
          <div class="mb-8">
            <img src="/images/img_footer_logo.png" 
                 alt="Acentria Global Consulting" 
                 class="h-16 w-auto mb-8">
          </div>
          
          <!-- Social Media Icons -->
          <div class="flex space-x-4">
            <a href="#" class="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-red-600 transition-colors">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>
              </svg>
            </a>
            <a href="#" class="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-red-600 transition-colors">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M22.46 6c-.77.35-1.6.58-2.46.69.88-.53 1.56-1.37 1.88-2.38-.83.5-1.75.85-2.72 1.05C18.37 4.5 17.26 4 16 4c-2.35 0-4.27 1.92-4.27 4.29 0 .34.04.67.11.98C8.28 9.09 5.11 7.38 3 4.79c-.37.63-.58 1.37-.58 2.15 0 1.49.75 2.81 1.91 3.56-.71 0-1.37-.2-1.95-.5v.03c0 2.08 1.48 3.82 3.44 4.21a4.22 4.22 0 0 1-1.93.07 4.28 4.28 0 0 0 4 2.98 8.521 8.521 0 0 1-5.33 1.84c-.34 0-.68-.02-1.02-.06C3.44 20.29 5.7 21 8.12 21 16 21 20.33 14.46 20.33 8.79c0-.19 0-.37-.01-.56.84-.6 1.56-1.36 2.14-2.23z"/>
              </svg>
            </a>
            <a href="#" class="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-red-600 transition-colors">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
            </a>
            <a href="#" class="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-red-600 transition-colors">
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24.009 12.017 24.009c6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001.012.001z"/>
              </svg>
            </a>
          </div>
        </div>

        <!-- Useful Links -->
        <div>
          <h3 class="text-xl font-bold mb-6">Useful Links</h3>
          <ul class="space-y-4">
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors">Home</a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors">Become Our Agent</a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors">Access Account</a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors">Technical Support</a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors">Terms & Conditions</a></li>
          </ul>
        </div>

        <!-- Services -->
        <div>
          <h3 class="text-xl font-bold mb-6">Services</h3>
          <ul class="space-y-4">
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors flex items-center">
              <span class="w-2 h-2 bg-red-600 rounded-full mr-3"></span>Insurance
            </a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors flex items-center">
              <span class="w-2 h-2 bg-red-600 rounded-full mr-3"></span>Reinsurance
            </a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors flex items-center">
              <span class="w-2 h-2 bg-red-600 rounded-full mr-3"></span>Product Management
            </a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors flex items-center">
              <span class="w-2 h-2 bg-red-600 rounded-full mr-3"></span>Technology
            </a></li>
            <li><a href="#" class="text-gray-300 hover:text-red-400 transition-colors flex items-center">
              <span class="w-2 h-2 bg-red-600 rounded-full mr-3"></span>Investment
            </a></li>
          </ul>
        </div>

        <!-- Contact Us -->
        <div>
          <h3 class="text-xl font-bold mb-6">Contact Us</h3>
          <ul class="space-y-4">
            <li class="flex items-start">
              <svg class="w-5 h-5 text-red-600 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"/>
              </svg>
              <span class="text-gray-300">+254 705 200 222</span>
            </li>
            <li class="flex items-start">
              <svg class="w-5 h-5 text-red-600 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"/>
                <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"/>
              </svg>
              <span class="text-gray-300">info@acesure.com</span>
            </li>
            <li class="flex items-start">
              <svg class="w-5 h-5 text-red-600 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z"/>
              </svg>
              <span class="text-gray-300">P.O.Box 5864-00100 Nairobi</span>
            </li>
            <li class="flex items-start">
              <svg class="w-5 h-5 text-red-600 mr-3 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z"/>
              </svg>
              <span class="text-gray-300">West Park Towers,Westlands</span>
            </li>
          </ul>
        </div>
      </div>

      <!-- Divider -->
      <div class="border-t-2 border-red-600 my-8"></div>

      <!-- Copyright -->
      <div class="text-center space-y-2">
        <p class="text-gray-300">© Copyright 2025 Acensure. All Rights Reserved</p>
        <p class="text-gray-300">Powered by Acensure Technologies</p>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>
