// src/pages/Home/HeroSection.jsx
import React from 'react';
import Button from '../../components/ui/Button';

const HeroSection = () => {
  return (
    <section 
      className="w-full min-h-[400px] sm:min-h-[500px] md:min-h-[600px] lg:min-h-[856px] bg-cover bg-center bg-no-repeat relative"
      style={{ backgroundImage: "url('/images/img_rectangle_2.png')" }}
    >
      {/* Login Button - Top Right */}
      <div className="absolute top-4 right-4 sm:right-6 lg:right-7 z-10">
        <Button
          text="Login"
          text_font_size="10"
          text_font_family="Poppins"
          text_font_weight="500"
          text_line_height="15px"
          text_color="#c10c0c"
          fill_background_color="#ffffff"
          border_border="1 solid #c10c0c"
          border_border_radius="12px"
          padding="4px 28px"
          className="text-xs sm:text-sm"
          layout_align_self=""
          layout_width=""
          margin=""
          position=""
          layout_gap=""
          variant=""
          size=""
          onClick={() => {}}
        />
      </div>

      {/* Main Content Container */}
      <div className="w-full max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 pt-14">
        {/* Header Component would go here */}
        <div className="flex justify-between items-center mb-16 sm:mb-20 lg:mb-32">
          {/* Logo */}
          <img 
            src="/images/img_header_logo.png" 
            alt="Acentria Global Consulting Logo" 
            className="w-[100px] sm:w-[120px] lg:w-[134px] h-auto"
          />

          {/* Desktop Navigation */}
          <div className="hidden lg:flex items-center justify-between flex-1 max-w-[30%] ml-8">
            <div className="flex items-center space-x-8">
              {/* Generate Quote Dropdown */}
              <div className="flex items-center space-x-2 text-white hover:text-gray-300 transition-colors cursor-pointer">
                <span className="text-sm font-medium font-['Poppins']">Generate Quote</span>
                <img 
                  src="/images/img_vector.svg" 
                  alt="dropdown arrow" 
                  className="w-[10px] h-[5px]"
                />
              </div>

              {/* Claims */}
              <span className="text-white hover:text-gray-300 transition-colors cursor-pointer text-sm font-medium font-['Poppins']">
                Claims
              </span>
            </div>

            {/* Resources Dropdown */}
            <div className="flex items-center space-x-2 text-white hover:text-gray-300 transition-colors cursor-pointer">
              <span className="text-sm font-medium font-['Poppins']">Resources</span>
              <img 
                src="/images/img_vector.svg" 
                alt="dropdown arrow" 
                className="w-[10px] h-[5px]"
              />
            </div>
          </div>

          {/* Desktop CTA Button */}
          <div className="hidden lg:block">
            <Button
              text="Generate a quote"
              text_font_size="14"
              text_font_family="Poppins"
              text_font_weight="700"
              text_line_height="21px"
              text_color="#ffffff"
              fill_background_color="#d9d9d960"
              border_border="1 solid #ffffff"
              border_border_radius="5px"
              padding="6px 12px"
              layout_align_self=""
              layout_width=""
              margin=""
              position=""
              layout_gap=""
              variant=""
              size=""
              onClick={() => {}}
              className=""
            />
          </div>
        </div>

        {/* Hero Content */}
        <div className="flex flex-col items-start space-y-5 sm:space-y-6 lg:space-y-8 max-w-[54%] mb-16 sm:mb-20 lg:mb-32">
          <h1 className="text-[24px] sm:text-[32px] md:text-[40px] lg:text-[48px] font-semibold font-['Poppins'] leading-tight text-white">
            Your Trusted Global Consulting Partner
          </h1>
          
          <p className="text-[14px] sm:text-[16px] lg:text-[20px] font-semibold font-['Poppins'] leading-relaxed text-[#ffffffbc] max-w-full">
            Acensure is committed to empowering organizations with strategies that inspire confidence and drive growth. Whether you are looking to optimize risk management, enhance financial performance, or embrace digital transformation, we are here to guide you every step of the way.
          </p>

          <Button
            text="Generate a quote"
            text_font_size="14"
            text_font_family="Poppins"
            text_font_weight="700"
            text_line_height="21px"
            text_color="#ffffff"
            fill_background_color="#d9d9d960"
            border_border="1 solid #ffffff"
            border_border_radius="5px"
            padding="6px 12px"
            className="mt-4 sm:mt-6"
            layout_align_self=""
            layout_width=""
            margin=""
            position=""
            layout_gap=""
            variant=""
            size=""
            onClick={() => {}}
          />
        </div>

        {/* Pagination Dots */}
        <div className="flex items-center justify-center space-x-3 mb-8">
          <div className="w-3 h-3 bg-[#d9d9d9] rounded-full"></div>
          <div className="w-3 h-3 bg-[#d9d9d9] rounded-full"></div>
          <div className="w-[38px] h-3 bg-[#c10c0c] rounded-full"></div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;

// src/components/HeroSection.vue
<template>
  <section class="relative min-h-screen bg-cover bg-center bg-no-repeat" 
           style="background-image: url('/images/img_rectangle_2.png')">
    <!-- Header -->
    <header class="relative z-20 w-full">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-6">
          <!-- Logo -->
          <div class="flex-shrink-0">
            <img src="/images/img_header_logo.png" 
                 alt="Acentria Global Consulting" 
                 class="h-12 w-auto">
          </div>

          <!-- Desktop Navigation -->
          <nav class="hidden lg:flex items-center space-x-8">
            <div class="flex items-center space-x-2 text-white hover:text-red-400 cursor-pointer transition-colors">
              <span class="font-medium">Generate Quote</span>
              <svg class="w-3 h-2" fill="currentColor" viewBox="0 0 10 5">
                <path d="M0 0l5 5 5-5z"/>
              </svg>
            </div>
            <a href="#" class="text-white hover:text-red-400 transition-colors font-medium">Claims</a>
            <div class="flex items-center space-x-2 text-white hover:text-red-400 cursor-pointer transition-colors">
              <span class="font-medium">Resources</span>
              <svg class="w-3 h-2" fill="currentColor" viewBox="0 0 10 5">
                <path d="M0 0l5 5 5-5z"/>
              </svg>
            </div>
            <div class="flex items-center space-x-2 text-white hover:text-red-400 cursor-pointer transition-colors">
              <span class="font-medium">Service</span>
              <svg class="w-3 h-2" fill="currentColor" viewBox="0 0 10 5">
                <path d="M0 0l5 5 5-5z"/>
              </svg>
            </div>
          </nav>

          <!-- CTA Buttons -->
          <div class="flex items-center space-x-4">
            <button class="hidden lg:block bg-white bg-opacity-20 border border-white text-white px-6 py-2 rounded-md hover:bg-opacity-30 transition-all font-medium">
              Generate a quote
            </button>
            <button class="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 transition-colors font-medium text-sm">
              Login
            </button>
          </div>

          <!-- Mobile menu button -->
          <button class="lg:hidden text-white p-2">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
            </svg>
          </button>
        </div>
      </div>
    </header>

    <!-- Hero Content -->
    <div class="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-32">
      <div class="max-w-3xl">
        <h1 class="text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">
          <span class="text-red-500">Your Trusted</span><br>
          <span class="text-white">Global</span><span class="text-white">Consulting Partner</span>
        </h1>
        
        <p class="text-xl text-white text-opacity-90 mb-8 leading-relaxed max-w-2xl">
          Acensure is committed to empowering organizations with strategies that inspire confidence and drive growth. Whether you're looking to optimize risk management, enhance financial performance, or embrace digital transformation, we are here to guide you every step of the way.
        </p>

        <div class="flex flex-col sm:flex-row gap-4">
          <button class="bg-red-600 text-white px-8 py-3 rounded-md hover:bg-red-700 transition-colors font-semibold">
            Generate a quote
          </button>
          <button class="bg-white bg-opacity-20 border border-white text-white px-8 py-3 rounded-md hover:bg-opacity-30 transition-all font-semibold">
            Work with Us
          </button>
        </div>
      </div>
    </div>

    <!-- Pagination dots -->
    <div class="absolute bottom-8 left-1/2 transform -translate-x-1/2 flex space-x-2 z-10">
      <div class="w-3 h-3 bg-white bg-opacity-50 rounded-full"></div>
      <div class="w-3 h-3 bg-white bg-opacity-50 rounded-full"></div>
      <div class="w-8 h-3 bg-red-600 rounded-full"></div>
    </div>

    <!-- Overlay -->
    <div class="absolute inset-0 bg-black bg-opacity-40"></div>
  </section>
</template>

<script>
export default {
  name: 'HeroSection'
}
</script>
