// src/pages/Home/ServicesSection.jsx
import React, { useState } from 'react';

const ServicesSection = () => {
  const [currentSlide, setCurrentSlide] = useState(0);

  const services = [
    {
      id: 1,
      title: "Risk & Insurance Consulting",
      image: "/images/img_rectangle_76.png",
      link: "#"
    },
    {
      id: 2,
      title: "Reinsurance Solutions",
      image: "/images/img_rectangle_77.png",
      link: "#"
    },
    {
      id: 3,
      title: "Actuarial Services",
      image: "/images/img_rectangle_78.png",
      link: "#"
    }
  ];

  return (
    <section className="w-full py-12 sm:py-16 lg:py-24">
      <div className="w-full max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center mb-8 sm:mb-12">
          <h2 className="text-[24px] sm:text-[32px] lg:text-[40px] font-bold font-['Inter'] leading-tight text-black mb-2">
            Our Core Services
          </h2>
          <div className="w-[38px] h-[1px] bg-black mx-auto">
            <img 
              src="/images/img_vector_20.svg" 
              alt="underline" 
              className="w-full h-full"
            />
          </div>
        </div>

        {/* Services Slider */}
        <div className="relative">
          {/* Desktop View - Show all 3 cards */}
          <div className="hidden lg:flex items-center justify-center space-x-9">
            {services?.map((service, index) => (
              <div key={service?.id} className="relative w-[336px] h-[326px] group cursor-pointer">
                {/* Service Image */}
                <img 
                  src={service?.image} 
                  alt={service?.title}
                  className="w-full h-full object-cover rounded-tl-[50px] rounded-tr-none rounded-br-none rounded-bl-none"
                />
                
                {/* Overlay Content */}
                <div className="absolute bottom-0 left-0 right-0 p-4 sm:p-6">
                  <div className="flex flex-col space-y-4 sm:space-y-6">
                    <h3 className="text-[16px] sm:text-[20px] font-semibold font-['Poppins'] leading-loose text-white drop-shadow-md">
                      {service?.title}
                    </h3>
                    
                    <div className="flex items-center justify-between">
                      <a 
                        href={service?.link}
                        className="text-[13px] sm:text-[15px] font-medium font-['Poppins'] leading-snug text-[#c10c0c] hover:text-[#ed1e26] transition-colors"
                      >
                        Read more
                      </a>
                      <img 
                        src="/images/img_vector_red_900.svg" 
                        alt="arrow right" 
                        className="w-3 h-2"
                      />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Mobile/Tablet View - Show 1 card at a time */}
          <div className="lg:hidden">
            <div className="relative w-full max-w-[336px] h-[326px] mx-auto group cursor-pointer">
              {/* Service Image */}
              <img 
                src={services?.[currentSlide]?.image} 
                alt={services?.[currentSlide]?.title}
                className="w-full h-full object-cover rounded-tl-[50px] rounded-tr-none rounded-br-none rounded-bl-none"
              />
              
              {/* Overlay Content */}
              <div className="absolute bottom-0 left-0 right-0 p-4 sm:p-6">
                <div className="flex flex-col space-y-4 sm:space-y-6">
                  <h3 className="text-[16px] sm:text-[20px] font-semibold font-['Poppins'] leading-loose text-white drop-shadow-md">
                    {services?.[currentSlide]?.title}
                  </h3>
                  
                  <div className="flex items-center justify-between">
                    <a 
                      href={services?.[currentSlide]?.link}
                      className="text-[13px] sm:text-[15px] font-medium font-['Poppins'] leading-snug text-[#c10c0c] hover:text-[#ed1e26] transition-colors"
                    >
                      Read more
                    </a>
                    <img 
                      src="/images/img_vector_red_900.svg" 
                      alt="arrow right" 
                      className="w-3 h-2"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Pagination Dots */}
        <div className="flex items-center justify-center space-x-3 sm:space-x-5 mt-8 sm:mt-12">
          {[0, 1, 2, 3]?.map((index) => (
            <button
              key={index}
              onClick={() => setCurrentSlide(index % services?.length)}
              className={`h-[10px] rounded-[5px] transition-all duration-300 ${
                index === 0 
                  ? 'w-[70px] bg-[#c10c0c]' 
                  : 'w-[70px] bg-[#b7b7b98c] hover:bg-[#c10c0c]'
              }`}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default ServicesSection;

// src/components/ServicesSection.vue
<template>
  <section class="py-20 bg-gray-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Section Header -->
      <div class="text-center mb-16">
        <h2 class="text-4xl lg:text-5xl font-bold text-gray-900 mb-4">Our Core Services</h2>
        <div class="w-16 h-1 bg-red-600 mx-auto"></div>
      </div>

      <!-- Services Grid -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
        <!-- Risk & Insurance Consulting -->
        <div class="relative group cursor-pointer">
          <div class="relative h-80 rounded-3xl overflow-hidden">
            <img src="https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600" 
                 alt="Risk & Insurance Consulting" 
                 class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300">
            <div class="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"></div>
            <div class="absolute bottom-6 left-6 right-6">
              <h3 class="text-xl font-semibold text-white mb-3">Risk & Insurance Consulting</h3>
              <div class="flex items-center justify-between">
                <span class="text-red-400 font-medium">Read more</span>
                <svg class="w-4 h-4 text-red-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"/>
                </svg>
              </div>
            </div>
          </div>
        </div>

        <!-- Reinsurance Solutions -->
        <div class="relative group cursor-pointer">
          <div class="relative h-80 rounded-3xl overflow-hidden">
            <img src="https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600" 
                 alt="Reinsurance Solutions" 
                 class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300">
            <div class="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"></div>
            <div class="absolute bottom-6 left-6 right-6">
              <h3 class="text-xl font-semibold text-white mb-3">Reinsurance Solutions</h3>
              <div class="flex items-center justify-between">
                <span class="text-red-400 font-medium">Read more</span>
                <svg class="w-4 h-4 text-red-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"/>
                </svg>
              </div>
            </div>
          </div>
        </div>

        <!-- Actuarial Services -->
        <div class="relative group cursor-pointer">
          <div class="relative h-80 rounded-3xl overflow-hidden">
            <img src="https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=600" 
                 alt="Actuarial Services" 
                 class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300">
            <div class="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"></div>
            <div class="absolute bottom-6 left-6 right-6">
              <h3 class="text-xl font-semibold text-white mb-3">Actuarial Services</h3>
              <div class="flex items-center justify-between">
                <span class="text-red-400 font-medium">Read more</span>
                <svg class="w-4 h-4 text-red-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"/>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Pagination dots -->
      <div class="flex justify-center space-x-2">
        <div class="w-16 h-2 bg-red-600 rounded-full"></div>
        <div class="w-16 h-2 bg-gray-300 rounded-full"></div>
        <div class="w-16 h-2 bg-gray-300 rounded-full"></div>
        <div class="w-16 h-2 bg-gray-300 rounded-full"></div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'ServicesSection'
}
</script>
